### ISSUE TITLE
Please implement option to disable test cleanup

### ISSUE THREAD

**Issue by lucasnoordzij** [Capgemini/powerapps-specflow-bindings#104]
Currently when creating anything through JSON methods the data is removed after succesfully running the test.

I would like to have the option for a JSON scenario to keep the inserted data. 

So:
Scenario: Create contact
Given I have created 'Test Contact'
Test Passes
Open D365 
Check to see that record was indeed created and not deleted after test run

**Comment by ewingjm** [comment]
Closed by #119
