### ISSUE TITLE
Full automated test code coverage

### ISSUE THREAD

**Issue by ewingjm** [Capgemini/powerapps-specflow-bindings#18]
To enable continuous deployment and leave pre-release, we should have full code coverage of the bindings in the automated test project. It also needs clarified in the contribution guidelines that any changes are expected to have accompanying code coverage.

**Comment by ewingjm** [comment]
It's likely we may need to look into including a custom app that we can test against. The current tests are dependent on Dynamics 365 modules being installed and the Dynamics 365 apps probably don't provide all the possible permutations that we need to provide full coverage.

**Comment by ewingjm** [comment]
@DavidRcapgemini @markcunninghamuk I've gone through the bindings and I suggest we create a _cap_PowerAppsSpecFlowBindings_Mock_ solution with the following -

- [ ] Multiple business process flows for an entity
  - [ ] Multiple stages for a business process flow
  - [ ] Text. option set, multi-select option set, boolean, numeric, currency, datetime and lookup fields on a business process flow
  - [ ] A business process flow error (possibly a mandatory boolean field in a stage will allow for this)
- [ ] Multiple dashboards
- [ ] Two entities
  - [ ] A one-to-many relationship
  - [ ] a many-to-many relationship
  - [ ] Text, option set, boolean, numeric, currency, datetime and lookup fields on a form
  - [ ] All of the above field types (where applicable) on a form header
  - [ ] Multiple forms on an entity
  - [ ] Three tabs on a form, two visible, one hidden
  - [ ] Mandatory and optional fields
  - [ ] A form notification
  - [ ] An option set field on a form with multiple options
  - [ ] A read-only field
  - [ ] A visible field and hidden field on a form 
  - [ ] A sub-grid on a form with view selector enabled and text, option set, boolean, numeric, currency, datetime and lookup fields on a view
  - [ ] An entity configured for categorized search
  - [ ] A lookup dialog (the kind shown when using [Xrm.Utility.lookupObjects](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/lookupobjects))
  - [ ] A lookup on a form with view selector enabled and multiple views
  - [ ] A lookup on a form for multiple entities (e.g. customer or regarding field)
  - [ ] An entity enabled for quick create with a quick create form
  - [ ] Text, option set, boolean, numeric, currency, datetime and lookup fields on a quick create form
  - [ ] A timeline on a form for an entity enabled for activities

That should cover everything we need broadly, I'm sure we'll find more things that we need when writing the tests.

**Comment by markcunninghamuk** [comment]
Thanks Max.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ewingjm** [comment]
Branch here https://github.com/Capgemini/powerapps-specflow-bindings/tree/test/full-test-coverage

**Comment by ewingjm** [comment]
@DavidRcapgemini @markcunninghamuk I've updated the UI test build to build and copy the mock solution. I've also added a SpecFlow `BeforeTestRun` hook to import the solution and an `AfterTestRun` hook to remove it.

Should be easy to start picking up tests now!
