### ISSUE TITLE
Perform test data setup as another user

### ISSUE THREAD

**Issue by ewingjm** [Capgemini/powerapps-specflow-bindings#4]
This would be useful if the user under test doesn't have permissions to create an entity within the test data e.g.

```gherkin
Given I am logged in as 'a standard user'
And 'a privileged user' has created 'something that I can read but I can't create'
```

**Comment by ewingjm** [comment]
Hi, @markcunninghamuk @DavidRcapgemini. I think both of you guys had some ideas on how this might work. We've already discussed this on Teams, but I think the GitHub issue is the best place for any discussions. From what I remember, we've landed on a couple of different options:

- A binding that creates and disposes a new `XrmApp` instance as the given user alias (probably force it to always be headless).
  - ✔ Quick to implement
  - ✔ No updates required to existing driver code
  - ❌ Slow, requires a new browser session to login
- Refactor the driver to not use `Xrm.WebApi.online` and instead handle authentication ourselves.
  - ✔ Fast, doesn't require a new browser session to login
  - ❌ Longer to implement
  - ❌ Significant changes to existing driver code

I believe we could implement this feature as the first option initially and subsequently implement the second option without introducing breaking changes. Depends how quickly the the feature is needed and how much time someone has to implement it.

**Comment by ewingjm** [comment]
We also talked about impersonation, which might be useful if we're creating records as users that aren't existing test users i.e. we don't have the credentials for them. I guess it would work for application users, too? In which case we'd just need to start asking for admin credentials in the config file.

**Comment by markcunninghamuk** [comment]
@ewingjm on the server side approach to this I did exactly that, I treated the clientid and secret as the username and password effectively. There was also option 3 to move the binding into C# Server side but was the last resort and a fallback (Which I know works as I use it on a current project). Apologies for the delay, Post Xmas has been busy.

Option 3 - Server Side
  - ✔ Proven to work
  - ✔ No updates required to existing driver code
  - ❌ Slower than client side
  - ❌ Teardown needs to handled by passing TestContext in specflow as you need to track all the objects created

**Comment by ewingjm** [comment]
Almost done with this now @markcunninghamuk. I've put the client ID and client secret in it's own config section as I figure we'll only ever need one application user. The users that we're impersonating will need to be in the users array as they'll be referred to by alias and we need to map that to a username for impersonation (ultimately, an Azure AD object ID - but I'm querying for that using the username). We won't need a password for these users, but if one is provided then they'll be available for both impersonation and logging in.

**Comment by ewingjm** [comment]
@markcunninghamuk  @DavidRcapgemini  Think this is code complete now - just need to prep Azure DevOps with the new environment variables etc.

Branch is feature/test-data-setup-as-named-user
