### ISSUE TITLE
Capgemini.PowerApps.SpecFlowBindings\bin\lib\driver.js was not found

### ISSUE THREAD

**Issue by thathi** [Capgemini/powerapps-specflow-bindings#53]
## Describe the bug
Not able to build the latest code

## To reproduce
Clone github repo and build the solution

## Expected behaviour
build should be succeeded 

## Screenshots
![image](https://user-images.githubusercontent.com/15817637/102336235-d6655780-3f88-11eb-8b55-ea1dbba3c905.png)

## Environment (please complete the following information):
NA

## Additional context
NA

**Comment by ewingjm** [comment]
Hi, @thathi. It looks like there is an issue running the npm build task in the driver project. Can you try running `npm run build` from the command line in the driver folder? That should result in a better error message.

**Comment by thathi** [comment]
Thanks @ewingjm Its my bad node was'nt there on my system now it is compliling okay.
