### ISSUE TITLE
[EnititySteps]-> Assign to a user or team test failing with an error

### ISSUE THREAD

**Issue by thathi** [Capgemini/powerapps-specflow-bindings#54]
## Describe the bug
Trying to run scenario : Assign to a user or team

it could be something to with my setup or the test data setup.

## To reproduce

_Steps to reproduce the behaviour._
Scenario: Assign to a user or team
	Given I have created 'a team'
	And I have created 'a secondary mock record'
	And I have opened 'the secondary mock record'
	When I assign the record to a team named 'A team'
	Then I can see a value of 'A team' in the 'ownerid' lookup field

## Expected behaviour
Test should be green

## Screenshots
![image](https://user-images.githubusercontent.com/15817637/102500148-e73ec780-4073-11eb-964d-33483459c3a6.png)

## Environment (please complete the following information):
Running in a trail instance with Mock Record solution import

## Additional context
using branch test/full-test-coverage with latest EasyRepro devlope branch code.

**Comment by ewingjm** [comment]
Hey, @thathi. We've got quite a few failures on this branch at the moment - just waiting for the latest version of EasyRepro to be pushed with my PRs to resolve them. 

This particularly test I'm going to change to take out the assertion at the end. The assertion is already tested in another scenario so I don't feel like it's adding much here. I think we're going to have to live with the error dialog (as long as it doesn't fail the test run) unless we want to put in a binding in the test project to assign the team a role.

**Comment by thathi** [comment]
Thanks @ewingjm that make sense.
