### ISSUE TITLE
Dont want testdata cleanup if the test is failed

### ISSUE THREAD

**Issue by thathi** [Capgemini/powerapps-specflow-bindings#72]
## Is your feature request related to a problem? Please describe
It would be handy to have the test data to investigate any flaky test failures either in local or pipeline

## Describe the solution you'd like
 [AfterScenario(Order = 1)]
        public static void TestCleanup()
        {
            try
            {
                if (this.scenarioContext.ScenarioExecutionStatus != ScenarioExecutionStatus.TestError)
                TestDriver.DeleteTestData();
            }
            catch (WebDriverException)
            {
                // Ignore - tests might have failed before driver was initialised.
            }
            finally
            {
                Quit();
            }
        }

**Comment by ewingjm** [comment]
Closed by #119
