### ISSUE TITLE
Bypass login where same user is reused

### ISSUE THREAD

**Issue by ewingjm** [Capgemini/powerapps-specflow-bindings#86]
## Is your feature request related to a problem? Please describe

The majority of our test run time is spent logging in. This includes where we've got the same user used in multiple tests.

## Describe the solution you'd like

It's possible to pass a Chrome profile folder to the Chrome web driver. Perhaps we could create a new profile for each test user at the beginning of the test run.

## Additional context

This should also speed up the tests as it will store other cached files.

**Comment by bancey** [comment]
Closing as #87 has been merged
